FROM ghcr.io/astral-sh/uv:python3.12-slim

# 使用国内 PyPI 镜像源
ENV UV_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
ENV UV_EXTRA_INDEX_URL=https://mirrors.aliyun.com/pypi/simple

WORKDIR /app

COPY pyproject.toml uv.lock /app/
RUN uv sync --no-dev --frozen

COPY . /app
ENTRYPOINT [ "uv", "run", "main.py" ]
